### ISSUE TITLE
'make build' fails

### ISSUE THREAD

**Issue by stevekm** [seqeralabs/nf-tower#220]
When I try to use `make build` as described in the README, it fails with the following errors:

```
$ make build
./gradlew assemble

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/kellys5/projects/nextflow-tower-dev/nf-tower/settings.gradle'

* What went wrong:
Could not compile settings file '/Users/kellys5/projects/nextflow-tower-dev/nf-tower/settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 57

  java.lang.IllegalArgumentException: Unsupported class file major version 57
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:184)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:152)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:273)
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
        at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:254)
        at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:
...
...
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:830)

  1 error


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 674ms
make: *** [build] Error 1
```

I am running macOS 10.12, with this Java:

```
$ java -version
java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```
(which I downloaded from here: https://www.oracle.com/java/technologies/javase-jdk13-downloads.html)

**Comment by pditommaso** [comment]
Only tested on Java 8. I've added a note in the readme 3ede5d0e.

**Comment by stevekm** [comment]
Thanks. I had a really hard time finding the correct version of Java for download, I ended up using this one and it is working:

https://anaconda.org/anaconda/openjdk/8.0.152/download/osx-64/openjdk-8.0.152-h393ad39_1.tar.bz2

**Comment by pditommaso** [comment]
The home of the JDK is http://openjdk.java.net/install/. 

Then like Linux there exist man different distributions, eg. https://www.azul.com/downloads/zulu-community/

**Comment by stevekm** [comment]
Oh yeah I saw that but they don't actually have a version of Java 8 [available for download](https://jdk.java.net/archive/); I can't use `sudo` or `apt-get` in the HPC where I'll eventually be deploying this to.

**Comment by pditommaso** [comment]
On Linux you can install with the distribution package manager at in the link provider. On Mac it's is available on Oracle, web site or from alternative distributions, eg https://adoptopenjdk.net/releases.html
