### ISSUE TITLE
Blank page at localhost:8000

### ISSUE THREAD

**Issue by dweemx** [seqeralabs/nf-tower#249]
Hi,

I'm trying to launch nf-tower from my local computer.
Backend and client seem to be running but when I browse to http://localhost:8000, it's blank

Here is my log:
```
make run
docker-compose up
Starting nf-tower_backend_1 ... done
Starting nf-tower_frontend_1 ... done
Attaching to nf-tower_backend_1, nf-tower_frontend_1
backend_1   | 14:36:55.678 [main] INFO  io.seqera.tower.Application - ++ Tower backend starting ++ System: Linux 4.15.0-112-generic; Runtime: Groovy 2.5.8 on OpenJDK 64-Bit Server VM 1.8.0_252-b09; Encoding: ANSI_X3.4-1968 (ANSI_X3.4-1968); 
frontend_1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
frontend_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
backend_1   | 14:36:55.878 [main] WARN  i.m.context.env.DefaultEnvironment - Unable to load properties file: tower
frontend_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
frontend_1  | 10-listen-on-ipv6-by-default.sh: error: IPv6 listen already enabled
frontend_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
frontend_1  | /docker-entrypoint.sh: Configuration complete; ready for start up
backend_1   | 14:36:56.693 [main] INFO  i.m.c.h.g.HibernateDatastoreFactory - Starting GORM for Hibernate
backend_1   | 14:36:58.158 [main] INFO  org.hibernate.Version - HHH000412: Hibernate Core {5.4.10.Final}
backend_1   | 14:36:58.285 [main] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 6.0.18.Final
backend_1   | 14:36:58.303 [main] INFO  o.h.v.i.engine.ConfigurationImpl - HV000002: Ignoring XML configuration.
backend_1   | 14:36:58.496 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
backend_1   | 14:36:58.622 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
backend_1   | 14:37:00.905 [main] INFO  o.h.v.i.engine.ConfigurationImpl - HV000002: Ignoring XML configuration.
backend_1   | 14:37:01.668 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type  [io.seqera.tower.service.mail.MailServiceImpl]
backend_1   | 
backend_1   | Message: Could not resolve placeholder ${TOWER_SMTP_USER}
backend_1   | Path Taken: ApplicationListener.setDispatcher([ApplicationEventDispatcher dispatcher]) --> ApplicationEventDispatcherImpl.setEventPublisher([AuditEventPublisher eventPublisher]) --> AuditEventPublisher.setMailService([MailService mailService]) --> MailServiceImpl.setConfig([MailerConfig config])
backend_1   | io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.seqera.tower.service.mail.MailServiceImpl]
backend_1   | 
backend_1   | Message: Could not resolve placeholder ${TOWER_SMTP_USER}
backend_1   | Path Taken: ApplicationListener.setDispatcher([ApplicationEventDispatcher dispatcher]) --> ApplicationEventDispatcherImpl.setEventPublisher([AuditEventPublisher eventPublisher]) --> AuditEventPublisher.setMailService([MailService mailService]) --> MailServiceImpl.setConfig([MailerConfig config])
backend_1   | 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1719)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2402)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2084)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2058)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1095)
backend_1   | 	at io.micronaut.context.AbstractBeanDefinition.getBeanForMethodArgument(AbstractBeanDefinition.java:1587)
backend_1   | 	at io.micronaut.context.AbstractBeanDefinition.getBeanForMethodArgument(AbstractBeanDefinition.java:871)
backend_1   | 	at io.seqera.tower.service.mail.$MailServiceImplDefinition.injectBean(Unknown Source)
backend_1   | 	at io.seqera.tower.service.mail.$MailServiceImplDefinition.build(Unknown Source)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1693)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2402)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2084)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2058)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1095)
backend_1   | 	at io.micronaut.context.AbstractBeanDefinition.getBeanForMethodArgument(AbstractBeanDefinition.java:1587)
backend_1   | 	at io.micronaut.context.AbstractBeanDefinition.getBeanForMethodArgument(AbstractBeanDefinition.java:871)
backend_1   | 	at io.seqera.tower.service.audit.$AuditEventPublisherDefinition.injectBean(Unknown Source)
backend_1   | 	at io.seqera.tower.service.audit.$AuditEventPublisherDefinition.build(Unknown Source)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1693)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2402)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2084)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2058)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1095)
backend_1   | 	at io.micronaut.context.AbstractBeanDefinition.getBeanForMethodArgument(AbstractBeanDefinition.java:1587)
backend_1   | 	at io.micronaut.context.AbstractBeanDefinition.getBeanForMethodArgument(AbstractBeanDefinition.java:871)
backend_1   | 	at io.seqera.tower.events.$ApplicationEventDispatcherImplDefinition.injectBean(Unknown Source)
backend_1   | 	at io.seqera.tower.events.$ApplicationEventDispatcherImplDefinition.build(Unknown Source)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1693)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2402)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2084)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2058)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1095)
backend_1   | 	at io.micronaut.context.AbstractBeanDefinition.getBeanForMethodArgument(AbstractBeanDefinition.java:1587)
backend_1   | 	at io.micronaut.context.AbstractBeanDefinition.getBeanForMethodArgument(AbstractBeanDefinition.java:871)
backend_1   | 	at io.seqera.tower.events.$ApplicationListenerDefinition.injectBean(Unknown Source)
backend_1   | 	at io.seqera.tower.events.$ApplicationListenerDefinition.build(Unknown Source)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1693)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2402)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2084)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2058)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:618)
backend_1   | 	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.getTarget(DefaultBeanContext.java:2968)
backend_1   | 	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2989)
backend_1   | 	at io.micronaut.aop.chain.AdapterIntroduction.intercept(AdapterIntroduction.java:81)
backend_1   | 	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
backend_1   | 	at io.seqera.tower.events.ApplicationListener$ApplicationEventListener$onStartup1$Intercepted.onApplicationEvent(Unknown Source)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1145)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:219)
backend_1   | 	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:188)
backend_1   | 	at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
backend_1   | 	at io.micronaut.runtime.Micronaut.run(Micronaut.java:294)
backend_1   | 	at io.micronaut.runtime.Micronaut.run(Micronaut.java:280)
backend_1   | 	at io.seqera.tower.Application.main(Application.groovy:40)
backend_1   | Caused by: io.micronaut.context.exceptions.ConfigurationException: Could not resolve placeholder ${TOWER_SMTP_USER}
backend_1   | 	at io.micronaut.context.env.DefaultPropertyPlaceholderResolver$PlaceholderSegment.getValue(DefaultPropertyPlaceholderResolver.java:283)
backend_1   | 	at io.micronaut.context.env.DefaultPropertyPlaceholderResolver.resolveRequiredPlaceholders(DefaultPropertyPlaceholderResolver.java:95)
backend_1   | 	at io.micronaut.context.env.PropertySourcePropertyResolver.resolvePlaceHoldersIfNecessary(PropertySourcePropertyResolver.java:706)
backend_1   | 	at io.micronaut.context.env.PropertySourcePropertyResolver.resolveSubMap(PropertySourcePropertyResolver.java:453)
backend_1   | 	at io.micronaut.context.env.PropertySourcePropertyResolver.resolveSubMap(PropertySourcePropertyResolver.java:425)
backend_1   | 	at io.micronaut.context.env.PropertySourcePropertyResolver.getProperty(PropertySourcePropertyResolver.java:297)
backend_1   | 	at io.micronaut.context.DefaultApplicationContext.getProperty(DefaultApplicationContext.java:208)
backend_1   | 	at io.micronaut.context.AbstractBeanDefinition.resolveValue(AbstractBeanDefinition.java:1612)
backend_1   | 	at io.micronaut.context.AbstractBeanDefinition.getValueForMethodArgument(AbstractBeanDefinition.java:785)
backend_1   | 	at io.seqera.mail.$MailerConfigDefinition.injectBean(Unknown Source)
backend_1   | 	at io.seqera.mail.$MailerConfigDefinition.build(Unknown Source)
backend_1   | 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1693)
backend_1   | 	... 52 common frames omitted
nf-tower_backend_1 exited with code 1
```

**Comment by pditommaso** [comment]
👇 

```
Could not resolve placeholder ${TOWER_SMTP_USER}
```


Add `TOWER_SMTP_USER` and `TOWER_SMTP_USER` env variables in the compose file.

**Comment by alirizaaribas-ibg** [comment]
I tried but failed:
```
export TOWER_SMTP_USER='myusername@myuniv.edu'
export TOWER_SMTP_PASSWORD='mypassword'
```

In application.yml I added but failed:
```
---
mail:
  from: "${TOWER_CONTACT_EMAIL:hello@foo.com}"
  smtp:
    host: "${TOWER_SMTP_HOST:email-smtp.eu-west-1.amazonaws.com}"
    port: "${TOWER_SMTP_PORT:587}"
    auth: "${TOWER_SMTP_AUTH:true}"
    user: "${TOWER_SMTP_USER:`myusername@myuniv.edu`}"
    password: "${TOWER_SMTP_PASSWORD:`mypassword`}"
    starttls:
      enable: true
      required: true
---
```

How can I add it to docker-compose.yml. Here is my file:
```
version: "3"
services:

  backend:
    image: tower-backend
    networks:
      - frontend
      - backend
    ports:
      - 8080:8080
    volumes:
      - $PWD:/work
    working_dir: /work

  frontend:
    build: ./tower-web
    networks:
      - frontend
    ports:
      - 8000:80
    depends_on:
      - backend

networks:
  frontend: {}
  backend: {}
```
