### ISSUE TITLE
Cannot access "Pipeline actions"

### ISSUE THREAD

**Issue by matthpich** [seqeralabs/nf-tower#257]
Hi,
I have had issues accessing the "Pipeline actions" page recently.
It returned errors such as this one: "Oops... Unable to process request - Error ID: 4zDUpVpjCZdu0hR5UhwqS9".
Submitting jobs ends up in the same manner.
Any idea where it might come from?

**Comment by pditommaso** [comment]
Thanks for reporting this. We have just applied a patch. Could you please confirm if it solves the problem?

**Comment by matthpich** [comment]
So far so good with the "Pipeline actions", but I still have similar issues:
- when submitting a job through tower with curl (for instance, error id QMjOJl26YN1gD6wRjVGL4)
- when designing a "New pipeline action", the workflow is not found and an error is reported (for instance, error id 7Nx8DI0sZi4WSv8jbZtK4D)

**Comment by pditommaso** [comment]
This seems related to malformed configuration in your pipeline:

```
java.lang.Exception: Project config file is malformed -- Cause: No signature of method: java.math.BigDecimal.call() is applicable for argument types: (ConfigObject) values: [[:]]
Possible solutions: scale(), wait(), abs(), ulp(), abs(), any()
	at nextflow.scm.AssetManager.getManifest0(AssetManager.groovy:449)
	at nextflow.scm.AssetManager.memoizedMethodPriv$getManifest(AssetManager.groovy:428)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
java.lang.Exception: Project config file is malformed -- Cause: No signature of method: java.math.BigDecimal.call() is applicable for argument types: (ConfigObject) values: [[:]]
Possible solutions: scale(), wait(), abs(), ulp(), abs(), any()
	at nextflow.scm.AssetManager.getManifest0(AssetManager.groovy:449)
	at nextflow.scm.AssetManager.memoizedMethodPriv$getManifest(AssetManager.groovy:428)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
```

 but I agree that it should be better reported

**Comment by matthpich** [comment]
Indeed! I should not have requested less than 1GB of RAM.
Thanks a huge lot for your help @pditommaso
