### ISSUE TITLE
Bug: nextflow head node not responding when dealing with many processes 

### ISSUE THREAD

**Issue by jfnavarro** [seqeralabs/nf-tower#291]
Hi! 

I have stumbled upon this issue several times when running `sarek` (nf-core) on multiple
samples. Some parts of `sarek` spawn hundreds of processes and the `nextflow` job running
in the head node seems to fail with a `Java Out of Memory` error which causes the application
to detach. Needless to say that I have tried to increase the number of CPUs and memory 
in the head node but I still get the same error. I believe the Java heap memory allocation does
not scale up with the requested memory in the head node? 

Unfortunately, I am not able to retrieve the log/stdout files from `tower.nf` but this is the error
message that I always get:

```Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-1"
Exception in thread "Tower-thread" java.lang.OutOfMemoryError: Java heap space
WARN: Failed to publish file: /scitron/scratch/55DEoQC0WjTfzp/f8/9eb136c7d503fe9c6ae64dde5900a0/B20-1088.pileup; to: /scitron/results3/VariantCalling/B20-1088/Control-FREEC/B20-1088.pileup [copy] -- See log file for details
Exception in thread "Task monitor" org.codehaus.groovy.runtime.InvokerInvocationException: java.lang.OutOfMemoryError: Java heap space
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:113)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
    at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
    at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
    at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
    at nextflow.processor.TaskPollingMonitor$_start_closure2.doCall(TaskPollingMonitor.groovy:293)
    at nextflow.processor.TaskPollingMonitor$_start_closure2.call(TaskPollingMonitor.groovy)
    at groovy.lang.Closure.run(Closure.java:493)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.OutOfMemoryError: Java heap space```

**Comment by jfnavarro** [comment]
I am actually leaning towards the thinking that the issue may be related to the size of the file and not the number of processes

**Comment by jfnavarro** [comment]
I played around with the Batch configuration in Nextflow (https://www.nextflow.io/docs/latest/config.html#config-aws-batch) and it seemed to solve the issue. I haven't tested it thoroughly though. I specifically tuned the `maxTransferAttempts`, the `uploadMaxThreads` and the `uploadChunkSize` parameters. I still think that this should be something to look into.

**Comment by pditommaso** [comment]
The Java OOM could be related to the S3 file transfers. Have you tried enabling the Fusion mounts feature when creating the Compute environment? It bypasses the need for copying data from the S3 bucket.
