### ISSUE TITLE
Unexpected response code 400 for request https://api.tower.nf/trace/1qAQYqsrc9kT4j/begin

### ISSUE THREAD

**Issue by JoseEspinosa** [seqeralabs/nf-tower#293]
I run a pipeline using nextflow-tower and it worked. Then, I run the same pipeline with a different parameterization from nextflow tower but now I am getting this error. However, I was able to run it on AWS without tower with  `NXF_VER=21.02.0-edge`.

The log of the nextflow-tower is the one below:

```bash
Mar-10 15:35:00.398 [main] DEBUG n.cloud.aws.batch.AwsBatchExecutor - [AWS BATCH] Executor options=AwsOptions(cliPath:/usr/local/bin/aws, storageClass:null, storageEncryption:null, remoteBinDir:/cbcrg-eu/work/tmp/4f/320f3b0f02b131fc3783344a138a87/bin, region:eu-west-1, maxParallelTransfers:16, maxTransferAttempts:1, delayBetweenAttempts:10s, fetchInstanceType:true, jobRole:null, volumes:[], awsCli:/usr/local/bin/aws --region eu-west-1)
Mar-10 15:35:00.460 [main] DEBUG nextflow.processor.TaskProcessor - Creating *combiner* operator for each param(s) at index(es): [1]
Mar-10 15:35:00.546 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: awsbatch
Mar-10 15:35:00.547 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'awsbatch'
Mar-10 15:35:00.550 [main] DEBUG nextflow.processor.TaskProcessor - Creating *combiner* operator for each param(s) at index(es): [1]
Mar-10 15:35:00.565 [main] INFO  nextflow.Nextflow - 
Benchmark: bali_score

Mar-10 15:35:00.589 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: awsbatch
Mar-10 15:35:00.589 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'awsbatch'
Mar-10 15:35:00.601 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: awsbatch
Mar-10 15:35:00.601 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'awsbatch'
Mar-10 15:35:00.690 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: awsbatch
Mar-10 15:35:00.690 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'awsbatch'
Mar-10 15:35:00.945 [main] DEBUG nextflow.Session - Session aborted -- Cause: Unexpected response code 400 for request https://api.tower.nf/trace/3iTXdOZeammg7s/begin
Mar-10 15:35:00.984 [main] DEBUG nextflow.Session - The following nodes are still active:
  [operator] map
  [operator] map
  [operator] map
  [operator] cross
  [operator] map
  [operator] join
  [operator] ifEmpty
  [operator] map
  [operator] collectFile
  [operator] view

Mar-10 15:35:00.996 [main] DEBUG nextflow.cli.Launcher - Operation aborted
nextflow.exception.AbortOperationException: Unexpected response code 400 for request https://api.tower.nf/trace/3iTXdOZeammg7s/begin
	at io.seqera.tower.plugin.TowerClient.onFlowBegin(TowerClient.groovy:303)
	at nextflow.Session$_notifyFlowBegin_closure20.doCall(Session.groovy:1007)
	at nextflow.Session$_notifyFlowBegin_closure20.call(Session.groovy)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2318)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2303)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2344)
	at nextflow.Session.notifyFlowBegin(Session.groovy:1007)
	at nextflow.Session.fireDataflowNetwork(Session.groovy:442)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:216)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:297)
	at nextflow.cli.Launcher.run(Launcher.groovy:475)
	at nextflow.cli.Launcher.main(Launcher.groovy:657)
```

Thanks!

**Comment by pditommaso** [comment]
Umm, weird. can you try to run it using the command line with the same parameterization causing the problem?

**Comment by JoseEspinosa** [comment]
In local it runs:

`NXF_VER=21.02.0-edge nextflow run main.nf -params-file params-file-regressive.json -profile tower`

The params are the same as the ones I included in tower.

**Comment by pditommaso** [comment]
Can you share the command line and the parameters to replicate the problem?

**Comment by JoseEspinosa** [comment]
In local I run it with the following command on the `tower` branch of `https://github.com/cbcrg/nf-benchmark`:
`NXF_VER=21.02.0-edge --pipeline "regressive_alignment" --regressive_align false --align_methods "CLUSTALO" --evaluate false --skip_benchmark -profile tower`

On tower, I run also the branch `tower` of `https://github.com/cbcrg/nf-benchmark` with the following settings:

**Work directory**: `s3://cbcrg-eu/work`

**Config profile**: `tower`

**Pipeline parameters**: 
```json
{"pipeline": "regressive_alignment",
 "regressive_align": false,
 "align_methods": "CLUSTALO",
 "evaluate": false,
 "skip_benchmark": true
}
```

**Nextflow config file**: `aws.batch.cliPath='/usr/local/bin/aws'`

Thanks!!!

**Comment by Z-Zen** [comment]
I have also the same issue with Tower being installed on a local server. The issue appeared when I tried to launch the pipeline with `-resume` argument. Looking at `.nextflow.log` report:

```
Nov-10 09:36:54.996 [main] DEBUG nextflow.cli.Launcher - Operation aborted
nextflow.exception.AbortOperationException: Unexpected response code 400 for request http://groot:8000/api/trace/P9r5AbqO/begin
        at io.seqera.tower.plugin.TowerClient.onFlowBegin(TowerClient.groovy:326)
        at nextflow.Session$_notifyFlowBegin_closure20.doCall(Session.groovy:1012)
        at nextflow.Session$_notifyFlowBegin_closure20.call(Session.groovy)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2318)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2303)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2344)
        at nextflow.Session.notifyFlowBegin(Session.groovy:1012)
        at nextflow.Session.fireDataflowNetwork(Session.groovy:447)
        at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:216)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:302)
        at nextflow.cli.Launcher.run(Launcher.groovy:475)
        at nextflow.cli.Launcher.main(Launcher.groovy:657)
```

I had no problem launching the pipeline at first but caused an error on `-resume`.
Tower version: `Version 19.08.0_63a81b5.dirty`
Nextflow version: `version 21.04.3 build 5560`
